version: '3.8'

services:
  backend:
    build: ./backend
    container_name: seller_os_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - TZ=Asia/Seoul
      - PYTHONUNBUFFERED=1  # 🚀 파이썬 로그 버퍼링 강제 해제 (실시간 출력)
